apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: drawzy-postgresdb
  namespace: drawzy-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      tolerations:
        -   key: "env"
            operator: "Equal"
            value: "staging"
            effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "env"
                    operator: In 
                    values:
                      - staging
      containers:
        - name: postgresdb
          image: postgres:17.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name:  POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: drawzy-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: drawzy-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drawzy-secrets
                  key: POSTGRES_PASSWORD
